const explorers = {
  KMD: 'https://kmd.explorer.dexstats.info/',
  AXO: 'https://axo.explorer.dexstats.info/',
  ETOMIC: 'https://etomic.explorer.dexstats.info/',
  KOIN: 'https://koin.explorer.dexstats.info/',
  MESH: 'https://mesh.explorer.dexstats.info/',
  DEX: 'https://dex.explorer.dexstats.info/',
  SUPERNET: 'https://supernet.explorer.dexstats.info/',
  DION: 'https://explorer.dionpay.com/',
  CCL: 'https://ccl.explorer.dexstats.info/',
  KV: 'https://kv.explorer.dexstats.info/',
  CHAIN: 'https://chain.explorer.dexstats.info/',
  PGT: 'https://pgt.explorer.dexstats.info/',
  MSHARK: 'https://mshark.explorer.dexstats.info/',
  REVS: 'https://revs.explorer.dexstats.info/',
  PANGEA: 'https://pangea.explorer.dexstats.info/',
  JUMBLR: 'https://jumblr.explorer.dexstats.info/',
  BET: 'https://bet.explorer.dexstats.info/',
  CRYPTO: 'https://crypto.explorer.dexstats.info/',
  HODL: 'https://hodl.explorer.dexstats.info/',
  ILN: 'https://explorer.ilien.io/',
  BOTS: 'https://bots.explorer.dexstats.info/',
  MGW: 'https://mgw.explorer.dexstats.info/',
  WLC21: 'https://wlc21.explorer.dexstats.info/',
  COQUICASH: 'https://coquicash.explorer.dexstats.info/',
  BTCH: 'https://btch.explorer.dexstats.info/',
  HUSH3: 'https://hush3.explorer.dexstats.info/',
  NINJA: 'https://ninja.explorer.dexstats.info/',
  SEC: 'https://sec.explorer.dexstats.info/',
  THC: 'https://thc.explorer.dexstats.info/',
  KMDICE: 'https://kmdice.explorer.dexstats.info/',
  ZEXO: 'https://zex.explorer.dexstats.info/',
  KSB: 'https://ksb.explorer.dexstats.info/',
  OUR: 'https://our.explorer.dexstats.info/',
  MCL:  'https://mcl.explorer.dexstats.info/',
  RFOX: 'https://rfox.explorer.dexstats.info/',
  LABS: 'https://labs.explorer.dexstats.info/',
  VOTE2020: 'https://vote2020.explorer.dexstats.info/',
  RICK: 'https://rick.kmd.dev/',
  MORTY: 'https://morty.kmd.dev/',
  VRSC: 'https://vrsc.explorer.dexstats.info/',
  ZILLA: 'https://zilla.explorer.dexstats.info/',
  OOT: 'https://oot.explorer.dexstats.info/',
  // DP: '',
  // SHARK: '',
  // EQL: '',
  // PIZZA: '',
  // BEER: '',
  // DSEC: '',
};

export default explorers;